### ISSUE TITLE
python main.py执行，一个ip都没抓到啊

### ISSUE THREAD

**Issue by xubigshu** [jiehua233/ipproxy#1]
如题

**Comment by xubigshu** [comment]
抓到了，只是稍微慢点

**Comment by jiehua233** [comment]
@xubigshu 你可以 `tail -f ipproxy.log` 看一下

**Comment by jiehua233** [comment]
@xubigshu 如果慢的话，可以考虑加大 `etc/config.py` 里面的 `THREAD_NUM`和`PROCESS_NUM`，减少`TIMEOUT`的值，不过如果`TIMEOUT`太小的话，也可能导致抓取的ip数量比较少
