### ISSUE TITLE
你好，请问有没有时间出一个兼容Python3.0的版本

### ISSUE THREAD

**Issue by freedomofme** [jiehua233/ipproxy#2]
如题，谢谢

**Comment by jiehua233** [comment]
@freedomofme 暂时没有这方面的安排，不过关于python版本的问题，你可以用virtualenv解决

**Comment by freedomofme** [comment]
好的，谢谢你。
我没用过virtualenv，我晚些时间试试、

---

Best Regards
Huang Hanxiong
Software Engineering
School of Data and Computer Science
SUN YAT-SEN UNIVERSITY
Guangzhou GuangDong Province 
510006P.R. China

原始邮件
发件人:Chen Jiehuanotifications@github.com
收件人:jiehua233/ipproxyipproxy@noreply.github.com
抄送:Huangxiegeixiong@gmail.com
发送时间:2016年3月17日(周四) 17:30
主题:Re: [ipproxy] 你好，请问有没有时间出一个兼容Python3.0的版本 (#2)

@freedomofme 暂时没有这方面的安排，不过关于python版本的问题，你可以用virtualenv解决
